{
  "openapi": "3.0.1",
  "info": {
    "version": "1.0.0",
    "title": "SlimMom",
    "description": "API documentation for project 'SlimMom'",
    "license": {
      "name": "MIT",
      "url": "https://opensource.org/licenses/MIT"
    }
  },
  "consumes": ["application/json"],
  "produces": ["application/json"],
  "servers": [{ "url": "https://slim-mom-project.herokuapp.com" }],
  "tags": [
    {
      "name": "User",
      "description": "User endpoints"
    },
    {
      "name": "Products",
      "description": "Products endpoints"
    }
  ],

  "paths": {
    "/api/users/register": {
      "post": {
        "tags": ["User"],
        "summary": "Registration new user",
        "parameters": [],
        "requestBody": {
          "description": "Registration's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RegistrationRequest"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RegistrationResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)"
          },
          "404": {
            "description": "Not found"
          },
          "409": {
            "description": "Provided email already exist"
          },
          "500": {
            "description": "Server error"
          }
        }
      }
    },
    "/api/users/login": {
      "post": {
        "tags": ["User"],
        "summary": "Login user",
        "parameters": [],
        "requestBody": {
          "description": "Login object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/LoginRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/LoginResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not found"
          },
          "500": {
            "description": "Server error"
          }
        }
      }
    },
    "/api/users/logout": {
      "get": {
        "tags": ["User"],
        "summary": "Logout user",

        "security": [{ "Bearer": [] }],

        "responses": {
          "204": {
            "description": "Not Content"
          },

          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not found"
          },
          "500": {
            "description": "Server error"
          }
        }
      }
    },
    "/api/users/public": {
      "post": {
        "tags": ["User"],
        "summary": "Get public information on daily calories and a list of not recommended foods",
        "parameters": [],
        "requestBody": {
          "description": "Request object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/DailyRateRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DailyRateResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request"
          },
          "404": {
            "description": "Not found"
          },
          "500": {
            "description": "Server error"
          }
        }
      }
    },
    "/api/users/private": {
      "post": {
        "tags": ["User"],
        "summary": "Get private information on daily calories and a list of not recommended foods",

        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "Request object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/DailyRateRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DailyRateResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not found"
          },
          "500": {
            "description": "Server error"
          }
        }
      }
    },

    "/api/users/current": {
      "get": {
        "tags": ["User"],
        "summary": "Get information about the current user",
        "security": [{ "Bearer": [] }],
        "parameters": [
          {
            "in": "header",
            "name": "Authorization",
            "type": "string",
            "description": "The token issued to the current user.",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CurrentResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not found"
          },
          "500": {
            "description": "Server error"
          }
        }
      }
    },

    "/api/products/search": {
      "get": {
        "tags": ["Products"],
        "summary": "Search and get a list of products by query",
        "security": [{ "Bearer": [] }],
        "parameters": [
          {
            "in": "query",
            "name": "product",
            "type": "string",
            "description": "Enter name of the product you want to find (ukrainian)",
            "required": true
          }
        ],

        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProductsResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request"
          },
          "404": {
            "description": "Not found"
          },

          "500": {
            "description": "Server error"
          }
        }
      }
    },

    "/api/products": {
      "post": {
        "tags": ["Products"],
        "summary": "Add product",
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "Product's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/AddProductRequest"
              }
            }
          }
        },

        "responses": {
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AddProductResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request"
          },
          "404": {
            "description": "Not found"
          },

          "500": {
            "description": "Server error"
          }
        }
      }
    },
    "/api/products/{productId}": {
      "delete": {
        "tags": ["Products"],
        "summary": "Remove product",
        "security": [{ "Bearer": [] }],
        "parameters": [
          {
            "in": "path",
            "name": "productId",
            "type": "string",
            "description": "Product's id",
            "required": true
          }
        ],

        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad request"
          },
          "404": {
            "description": "Not found"
          },

          "500": {
            "description": "Server error"
          }
        }
      }
    },
    "/api/products/{date}": {
      "get": {
        "tags": ["Products"],
        "summary": "Get info of day",
        "security": [{ "Bearer": [] }],
        "parameters": [
          {
            "in": "path",
            "name": "date",
            "type": "string",
            "description": "Enter date YYYY-MM-DD",
            "required": true
          }
        ],

        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DateResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request"
          },
          "404": {
            "description": "Not found"
          },

          "500": {
            "description": "Server error"
          }
        }
      }
    }
  },

  "components": {
    "schemas": {
      "RegistrationRequest": {
        "type": "object",
        "required": ["name", "email", "password"],
        "properties": {
          "name": {
            "type": "string",
            "description": "User's name"
          },
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email"
          },
          "password": {
            "type": "string",
            "description": "User's password"
          }
        },
        "example": {
          "name": "User",
          "email": "user@example.com",
          "password": "qwe123456"
        }
      },

      "RegistrationResponse": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "User's name"
          },
          "email": {
            "type": "string",
            "description": "User's email"
          }
        },
        "example": { "name": "User", "email": "user@example.com" }
      },

      "LoginRequest": {
        "type": "object",
        "required": ["email", "password"],
        "properties": {
          "email": {
            "type": "string",
            "description": "User's email"
          },
          "password": {
            "type": "string",
            "description": "User's password"
          }
        },
        "example": {
          "email": "user@example.com",
          "password": "qwe123456"
        }
      },

      "LoginResponse": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "User's name"
          },
          "email": {
            "type": "string",
            "description": "User's email"
          },
          "token": {
            "type": "string",
            "description": "User's token"
          },
          "isCalculated": {
            "type": "boolean"
          }
        },
        "example": {
          "name": "User",
          "email": "user@example.com",
          "token": "JWT",
          "isCalculated": "false"
        }
      },

      "CurrentResponse": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "User's name"
          },
          "email": {
            "type": "string",
            "description": "User's email"
          },
          "isCalculated": {
            "type": "boolean",
            "description": "Whether the user's data has been processed in his profile in the database."
          }
        },
        "example": {
          "name": "User",
          "email": "user@example.com",
          "isCalculated": "false"
        }
      },

      "DailyRateRequest": {
        "type": "object",
        "required": [
          "currentWeight",
          "height",
          "age",
          "desiredWeight",
          "bloodType"
        ],
        "properties": {
          "currentWeight": {
            "type": "number",
            "description": "User's currentWeight (kg)"
          },
          "height": {
            "type": "number",
            "description": "User's height (cm)"
          },
          "age": {
            "type": "number",
            "description": "User's age",
            "min": 18
          },
          "desiredWeight": {
            "type": "number",
            "description": "User's desired weight (cm)"
          },
          "bloodType": {
            "type": "string",
            "description": "User's group blood"
          }
        },
        "example": {
          "currentWeight": 80,
          "height": 165,
          "age": 30,
          "desiredWeight": 70,
          "bloodType": 1
        }
      },

      "DailyRateResponse": {
        "type": "object",
        "properties": {
          "kcal": {
            "type": "number",
            "description": "User's daily calorie intake"
          },
          "productsNotRecommended": {
            "type": "array",
            "description": "User's list of not recommended products",
            "items": {
              "type": "string"
            }
          }
        },
        "example": {
          "kcal": 1420,
          "productsNotRecommended": [
            "Яйце куряче (жовток сухий)",
            "Горох маш Ярмарка Платинум",
            "Гречана крупа (ядриця) зелена",
            "Яйце куряче (варене всмятку)",
            "Омлет із сиром",
            "Яйце куряче (варене круто)",
            "Меланж яєчний",
            "Булгур"
          ]
        }
      },

      "ProductsResponse": {
        "type": "object",
        "properties": {
          "kcal": {
            "type": "number",
            "description": "Product's kcal/100g"
          },
          "weight": {
            "type": "number",
            "description": "Product's weight (100g)"
          },
          "title": {
            "type": "string",
            "description": "Product's title"
          },
          "id": {
            "type": "string",
            "description": "Product's id"
          }
        },
        "example": [
          {
            "kcal": 342,
            "weight": 100,
            "title": "Булгур",
            "id": "5d51694802b2373622ff5547"
          },
          {
            "kcal": 83,
            "weight": 100,
            "title": "Булгур приготований",
            "id": "5d51694802b2373622ff5549"
          }
        ]
      },

      "AddProductRequest": {
        "type": "object",
        "required": ["kcal", "weight", "title"],
        "properties": {
          "kcal": {
            "type": "number",
            "description": "Product's kcal/100g"
          },
          "weight": {
            "type": "number",
            "description": "Product's weight (g)"
          },
          "title": {
            "type": "string",
            "description": "Product's name"
          }
        },
        "example": {
          "kcal": 330,
          "weight": 150,
          "title": "Булгур Yelli з білими грибами"
        }
      },

      "AddProductResponse": {
        "type": "object",
        "properties": {
          "date": {
            "type": "string",
            "description": "Day's date"
          },
          "id": {
            "type": "string",
            "description": "Product's id"
          },
          "kcal": {
            "type": "number",
            "description": "Kcal consumed"
          },
          "weight": {
            "type": "number",
            "description": "Product's weight changed by the user"
          },
          "title": {
            "type": "string",
            "description": "Product's name"
          },
          "owner": {
            "type": "string",
            "description": "Owner's id product"
          }
        },
        "example": {
          "date": "2022-07-15",
          "_id": "5d51694802b2373622ff5548",
          "kcal": 330,
          "weight": 150,
          "title": "Булгур Yelli з білими грибами",
          "owner": "62d0a0578a552da90ca9d471"
        }
      },
      "DateResponse": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string",
            "description": "User's email"
          },
          "date": {
            "type": "string",
            "description": "Day's date"
          },
          "products": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "kcal": {
                  "type": "number",
                  "description": "Product's kcal"
                },
                "weight": {
                  "type": "number",
                  "description": "Product's weight"
                },
                "title": {
                  "type": "string",
                  "description": "Product's title"
                },
                "id": {
                  "type": "string",
                  "description": "Product's id"
                }
              }
            }
          },
          "dayNorm": {
            "type": "string",
            "description": "Calories per day"
          },
          "totalKcalPerDay": {
            "type": "number",
            "description": "Calories consumed per day"
          },
          "KcalRemain": {
            "type": "number",
            "description": "Calories left for the day"
          },
          "percentage": {
            "type": "string",
            "description": "Percentage of the daily norm"
          },
          "productsNotRecommended": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "User's list of not recommended products"
          }
        },
        "example": {
          "email": "user@example.com",
          "date": "2022-07-15",
          "products": [
            {
              "kcal": 380,
              "weight": 150,
              "title": "Мюслі Matti Горіх і Яблуко",
              "id": "5d51694802b2373622ff5589"
            },
            {
              "kcal": 89,
              "weight": 100,
              "title": "Яблуко печене солодке",
              "id": "5d51694902b2373622ff5c03"
            }
          ],
          "dayNorm": 1420,
          "totalKcalPerDay": 659,
          "kcalRemain": 1310,
          "percentage": 92,
          "productsNotRecommended": [
            "Яйце куряче (жовток сухий)",
            "Горох маш Ярмарка Платинум",
            "Гречана крупа (ядриця) зелена",
            "Яйце куряче (варене всмятку)",
            "Омлет із сиром",
            "Яйце куряче (варене круто)",
            "Меланж яєчний",
            "Булгур"
          ]
        }
      }
    },
    "securitySchemes": {
      "Bearer": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  }
}
